In [1]:
import numpy as np
from numpy import float32
import warnings
import os
import glob
import tensorflow as tf
import cv2
from sklearn import utils
from sklearn import preprocessing
import matplotlib.pyplot as plt
import Augmentor

import tensorflow.keras.backend as K
from tensorflow.keras.applications import *
from tensorflow.keras.layers import *
from tensorflow.keras.models import *
from tensorflow.keras.preprocessing import *
from tensorflow.keras.utils import *
from tensorflow.keras import layers
from tensorflow.keras.optimizers import Adam

from data_augmentation import *

In [2]:
os.environ["CUDA_VISIBLE_DEVICES"]="1"

In [3]:
TRAIN_DATA_DIR = './data/train'
VAL_DATA_DIR = './data/val'
TEST_DATA_DIR = './data/test'

AUG_TRAIN_DATA_DIR = './data_augmented/train'
AUG_VAL_DATA_DIR = './data_augmented/val'
AUG_TEST_DATA_DIR = './data_augmented/test'

CHECKPOINTS_DIR = './resnet50_weights/checkpoints/'

In [4]:
def delete_files(folder):
    for filename in os.listdir(folder):
        file_path = os.path.join(folder, filename)
        try:
            if os.path.isfile(file_path) or os.path.islink(file_path):
                os.unlink(file_path)
            elif os.path.isdir(file_path):
                shutil.rmtree(file_path)
        except Exception as e:
            print('Failed to delete %s. Reason: %s' % (file_path, e))

In [5]:
def augment_train_data():
    delete_files(f'{AUG_TRAIN_DATA_DIR}/positive')
    delete_files(f'{AUG_TRAIN_DATA_DIR}/negative')
    
    for subdir, dirs, files in os.walk(TRAIN_DATA_DIR):
        for file in files:
            filepath = os.path.join(subdir, file)
            img = np.load(filepath)
            # rotated_imgs = [rotate_img(img, 90), rotate_img(img, 180), rotate_img(img, 270)]
            # for idx, rot_img in enumerate(rotated_imgs):
            #     rotated_img_save = os.path.join(subdir, f'{file}_{idx}_rot')
            #     np.save(rotated_img_save, rot_img)

            fliplr_img = np.fliplr(img)
            flipud_img = np.flipud(img)
            folder = subdir.rsplit('/', 1)[1]
            cut_filename = file.rsplit('.', 1)[0]

            original_img_save = os.path.join(f'{AUG_TRAIN_DATA_DIR}/{folder}', cut_filename)
            fliplr_img_save = os.path.join(f'{AUG_TRAIN_DATA_DIR}/{folder}', f'{cut_filename}_fliplr')
            flipud_img_save = os.path.join(f'{AUG_TRAIN_DATA_DIR}/{folder}', f'{cut_filename}_flipud')

            np.save(original_img_save, img)
            np.save(fliplr_img_save, fliplr_img)
            np.save(flipud_img_save, flipud_img)

            # translated_img = translate(img)
            # translated_img_save = os.path.join(subdir, f'{file}_trans')
            # np.save(translated_img_save, translated_img)

In [6]:
# augment_train_data()

In [7]:
class CustomDataGen(tf.keras.utils.Sequence):
    
    def __init__(self, files_paths,
                 batch_size,
                 input_size=(128, 128, 1),
                 shuffle=True):
        
        self.files_paths = files_paths.copy()
        self.batch_size = batch_size
        self.input_size = input_size
        self.shuffle = shuffle
        
        self.n = len(self.files_paths)
        self.n_category = 2
        # self.n_name = df[y_col['name']].nunique()
        # self.n_type = df[y_col['type']].nunique()
    
    def on_epoch_end(self):
        if self.shuffle:
            np.random.shuffle(self.files_paths)
    
    def __getitem__(self, index):
        batches = self.files_paths[index * self.batch_size:(index + 1) * self.batch_size]
        X, y = self.__get_data(batches)        
        return X, y
    
    def __len__(self):
        return self.n // self.batch_size
    
    def __get_input(self, path):
        # image = preprocessing.normalize(np.load(path))
        image = np.load(path)
        image = cv2.resize(image, (128, 128), interpolation = cv2.INTER_AREA)
        return image

    def __get_output(self, path, num_classes=2):
        label = None
        folder = path.rsplit('/')[-2]
        if folder == 'positive':
            label = 1
        elif folder == 'negative':
            label = 0
        return tf.keras.utils.to_categorical(label, num_classes=num_classes)
    
    def __get_data(self, batches):
        # Generates data containing batch_size samples
        # path_batch = batches[self.X_col['path']]
        # category_batch = batches[self.y_col['type']]

        X_batch = np.asarray([self.__get_input(x) for x in batches])
        y_batch = np.asarray([self.__get_output(y, self.n_category) for y in batches])

        return X_batch, y_batch

In [8]:
def identity_block(input_tensor, kernel_size, filters, stage, block):
  
    filters1, filters2, filters3 = filters
    if K.image_data_format() == 'channels_last':
        bn_axis = 3
    else:
        bn_axis = 1
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'

    x = Conv2D(filters1, (1, 1), name=conv_name_base + '2a')(input_tensor)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2a')(x)
    x = Activation('relu')(x)

    x = Conv2D(filters2, kernel_size,
               padding='same', name=conv_name_base + '2b')(x)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2b')(x)
    x = Activation('relu')(x)

    x = Conv2D(filters3, (1, 1), name=conv_name_base + '2c')(x)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2c')(x)

    x = layers.add([x, input_tensor])
    x = Activation('relu')(x)
    return x

In [9]:
def conv_block(input_tensor, kernel_size, filters, stage, block, strides=(2, 2)):
   
    filters1, filters2, filters3 = filters
    if K.image_data_format() == 'channels_last':
        bn_axis = 3
    else:
        bn_axis = 1
    conv_name_base = 'res' + str(stage) + block + '_branch'
    bn_name_base = 'bn' + str(stage) + block + '_branch'

    x = Conv2D(filters1, (1, 1), strides=strides,
               name=conv_name_base + '2a')(input_tensor)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2a')(x)
    x = Activation('relu')(x)

    x = Conv2D(filters2, kernel_size, padding='same',
               name=conv_name_base + '2b')(x)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2b')(x)
    x = Activation('relu')(x)

    x = Conv2D(filters3, (1, 1), name=conv_name_base + '2c')(x)
    x = BatchNormalization(axis=bn_axis, name=bn_name_base + '2c')(x)

    shortcut = Conv2D(filters3, (1, 1), strides=strides,
                      name=conv_name_base + '1')(input_tensor)
    shortcut = BatchNormalization(axis=bn_axis, name=bn_name_base + '1')(shortcut)

    x = layers.add([x, shortcut])
    x = Activation('relu')(x)
    return x

In [10]:
def ResNet50(include_top=True, weights=None,
             input_tensor=None, input_shape=None,
             pooling=None,
             classes=2):
    """Instantiates the ResNet50 architecture.
    Optionally loads weights pre-trained
    on ImageNet. Note that when using TensorFlow,
    for best performance you should set
    `image_data_format="channels_last"` in your Keras config
    at ~/.keras/keras.json.
    The model and the weights are compatible with both
    TensorFlow and Theano. The data format
    convention used by the model is the one
    specified in your Keras config file.
    # Arguments
        include_top: whether to include the fully-connected
            layer at the top of the network.
        weights: one of `None` (random initialization)
            or "imagenet" (pre-training on ImageNet).
        input_tensor: optional Keras tensor (i.e. output of `layers.Input()`)
            to use as image input for the model.
        input_shape: optional shape tuple, only to be specified
            if `include_top` is False (otherwise the input shape
            has to be `(224, 224, 3)` (with `channels_last` data format)
            or `(3, 224, 244)` (with `channels_first` data format).
            It should have exactly 3 inputs channels,
            and width and height should be no smaller than 197.
            E.g. `(200, 200, 3)` would be one valid value.
        pooling: Optional pooling mode for feature extraction
            when `include_top` is `False`.
            - `None` means that the output of the model will be
                the 4D tensor output of the
                last convolutional layer.
            - `avg` means that global average pooling
                will be applied to the output of the
                last convolutional layer, and thus
                the output of the model will be a 2D tensor.
            - `max` means that global max pooling will
                be applied.
        classes: optional number of classes to classify images
            into, only to be specified if `include_top` is True, and
            if no `weights` argument is specified.
    # Returns
        A Keras model instance.
    # Raises
        ValueError: in case of invalid argument for `weights`,
            or invalid input shape.
    """
    if weights not in {'imagenet', None}:
        raise ValueError('The `weights` argument should be either '
                         '`None` (random initialization) or `imagenet` '
                         '(pre-training on ImageNet).')

    #if weights == 'imagenet' and include_top and classes != 15:
    #    raise ValueError('If using `weights` as imagenet with `include_top`'
    #                     ' as true, `classes` should be 15')

    # Determine proper input shape
    
    # input_shape = _obtain_input_shape(input_shape,
    #                                   default_size=256,
    #                                   min_size=197,
    #                                   data_format=K.image_data_format(),
    #                                   require_flatten=include_top)
    
    input_shape = (128, 128, 1)

    if input_tensor is None:
        img_input = Input(shape=input_shape)
    else:
        if not K.is_keras_tensor(input_tensor):
            img_input = Input(tensor=input_tensor, shape=input_shape)
        else:
            img_input = input_tensor
            
    print(K.image_data_format())
    if K.image_data_format() == 'channels_last':
        bn_axis = 3
    else:
        bn_axis = 1

    x = ZeroPadding2D((3, 3))(img_input)
    x = Conv2D(64, (7, 7), strides=(2, 2), name='conv1')(x)
    x = BatchNormalization(axis=bn_axis, name='bn_conv1')(x)
    x = Activation('relu')(x)
    x = MaxPooling2D((3, 3), strides=(2, 2))(x)

    x = conv_block(x, 3, [64, 64, 256], stage=2, block='a', strides=(1, 1))
    x = identity_block(x, 3, [64, 64, 256], stage=2, block='b')
    x = identity_block(x, 3, [64, 64, 256], stage=2, block='c')

    x = conv_block(x, 3, [128, 128, 512], stage=3, block='a')
    x = identity_block(x, 3, [128, 128, 512], stage=3, block='b')
    x = identity_block(x, 3, [128, 128, 512], stage=3, block='c')
    x = identity_block(x, 3, [128, 128, 512], stage=3, block='d')

    x = conv_block(x, 3, [256, 256, 1024], stage=4, block='a')
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block='b')
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block='c')
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block='d')
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block='e')
    x = identity_block(x, 3, [256, 256, 1024], stage=4, block='f')

    x = conv_block(x, 3, [512, 512, 2048], stage=5, block='a')
    x = identity_block(x, 3, [512, 512, 2048], stage=5, block='b')
    x = identity_block(x, 3, [512, 512, 2048], stage=5, block='c')

    x = AveragePooling2D((4, 4), name='avg_pool')(x)

#     # x = Flatten()(x)
#     # x = Dense(1, activation='sigmoid', name='fc2')(x)
    
    if include_top:
        x = Flatten()(x)
        x = Dense(2, activation='softmax', name='fc2')(x)
    else:
        if pooling == 'avg':
            x = GlobalAveragePooling2D()(x)
        elif pooling == 'max':
            x = GlobalMaxPooling2D()(x)

    # x = GlobalAveragePooling2D()(x)
    # x = Dense(2, activation = 'softmax')(x)

    # Ensure that the model takes into account
    # any potential predecessors of `input_tensor`.
    if input_tensor is not None:
        inputs = get_source_inputs(input_tensor)
    else:
        inputs = img_input
    # Create model.
    model = Model(inputs, x, name='resnet50')

    return model

In [11]:
train_files = []
for subdir, dirs, files in os.walk(AUG_TRAIN_DATA_DIR):
     for f in files:
        train_files.append(os.path.join(subdir, f))
train_files = np.array(train_files)

val_files = []
for subdir, dirs, files in os.walk(AUG_VAL_DATA_DIR):
     for f in files:
        val_files.append(os.path.join(subdir, f))
val_files = np.array(val_files)

test_files = []
for subdir, dirs, files in os.walk(AUG_TEST_DATA_DIR):
     for f in files:
        test_files.append(os.path.join(subdir, f))
test_files = np.array(test_files)

In [12]:
traingen = CustomDataGen(train_files, 64)
valgen = CustomDataGen(val_files, 64)

In [13]:
epochs = 100
batch_size = 64

model = ResNet50(include_top=True)
adam_fine = Adam(learning_rate=0.0005, beta_1=0.9, beta_2=0.999, decay=0.0002, amsgrad=False)

channels_last


2022-07-21 19:16:19.812286: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-21 19:16:20.439349: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 6656 MB memory:  -> device: 0, name: GeForce RTX 2080, pci bus id: 0000:82:00.0, compute capability: 7.5


In [14]:
model.compile(loss='categorical_crossentropy',optimizer=adam_fine,metrics=['accuracy'])

model.fit(traingen, validation_data = valgen, epochs=epochs)

Epoch 1/100


2022-07-21 19:16:27.534569: I tensorflow/stream_executor/cuda/cuda_dnn.cc:384] Loaded cuDNN version 8100
2022-07-21 19:16:28.231498: I tensorflow/core/platform/default/subprocess.cc:304] Start cannot spawn child process: No such file or directory
2022-07-21 19:16:28.236176: W tensorflow/stream_executor/gpu/asm_compiler.cc:111] *** WARNING *** You are using ptxas 10.0.145, which is older than 11.1. ptxas before 11.1 is known to miscompile XLA code, leading to incorrect results or invalid-address errors.

You may not need to update to CUDA 11.1; cherry-picking the ptxas binary is often sufficient.


78/78 [==============================] - 20s 145ms/step - loss: 1.2166 - accuracy: 0.4996 - val_loss: 3.0121 - val_accuracy: 0.5260
Epoch 2/100
78/78 [==============================] - 10s 130ms/step - loss: 0.7323 - accuracy: 0.5188 - val_loss: 0.8014 - val_accuracy: 0.5000
Epoch 3/100
78/78 [==============================] - 10s 130ms/step - loss: 0.7140 - accuracy: 0.5312 - val_loss: 0.8139 - val_accuracy: 0.4896
Epoch 4/100
78/78 [==============================] - 10s 131ms/step - loss: 0.7194 - accuracy: 0.5443 - val_loss: 0.8331 - val_accuracy: 0.4948
Epoch 5/100
78/78 [==============================] - 10s 131ms/step - loss: 0.7075 - accuracy: 0.5425 - val_loss: 0.7728 - val_accuracy: 0.4948
Epoch 6/100
78/78 [==============================] - 10s 131ms/step - loss: 0.6960 - accuracy: 0.5595 - val_loss: 0.8102 - val_accuracy: 0.4792
Epoch 7/100
78/78 [==============================] - 10s 130ms/step - loss: 0.6948 - accuracy: 0.5497 - val_loss: 0.7263 - val_accuracy: 0.4948
Epoc

In [15]:
model.save_weights(f'{CHECKPOINTS_DIR}/my_checkpoint')

In [ ]:
# test_x_pos = get_data_array(f'{TEST_DATA_DIR}/positive')
# test_x_neg = get_data_array(f'{TEST_DATA_DIR}/negative')
# test_x = np.append(test_x_pos, test_x_neg, axis=0)

# test_y_pos = np.ones((test_x_pos.shape[0]), dtype=int)

# test_y_neg = np.zeros((test_x_neg.shape[0]), dtype=int)
# test_y = np.append(test_y_pos, test_y_neg, axis=0)

In [78]:
testgen = CustomDataGen(test_files, batch_size)

In [73]:
test_data = []
test_data_y = []
for f in test_files:
    label = f.split('/')[-2]
    num_label = 0
    if label == 'positive':
        num_label = 1
    hot_enc_label = np.zeros(2)
    hot_enc_label[num_label] = 1
    test_data_y.append(hot_enc_label)
    image = np.load(f)
    image = cv2.resize(image, (128, 128), interpolation = cv2.INTER_AREA)
    image.reshape(128, 128, 1)
    test_data.append(image)
test_data = np.array(test_data)
test_data_y = np.array(test_data_y)

In [79]:
predictions = model.predict(testgen)

1/1 [==============================] - 2s 2s/step


In [80]:
preds = []
for idx, p in enumerate(predictions):
    p_largest = p.argmax()
    pred = np.zeros(2)
    pred[p_largest] = 1
    preds.append(pred)

In [81]:
preds

[array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([1., 0.]),
 array([0., 1.]),
 array([1., 0.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([1., 0.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([1., 0.]),
 array([1., 0.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([0., 1.]),
 array([1., 0.]),
 array([0., 1.]),
 array([0.